### ISSUE TITLE
How to train and test on our own datasets?

### ISSUE THREAD

**Issue by panboshui** [levayz/ProtoSAM#4]

**Comment by levayz** [comment]
If your data consists of .png/.jpg then look at the PolypDataset here:
https://github.com/levayz/ProtoSAM/blob/main/dataloaders/PolypDataset.py#L111

if its nifty youll need to put it in a directory with the following format: image_X.nii.gz and label_X.nii.gz where X is the number of the scan.
Use ManualAnnoDataset: https://github.com/levayz/ProtoSAM/blob/main/dataloaders/ManualAnnoDatasetv2.py
and provide it the base_dir of your dataset.
Also you need to update DATASET_INFO here: https://github.com/levayz/ProtoSAM/blob/main/dataloaders/dataset_utils.py.
